
    - name: Install legacy firefox from .deb
      apt: deb=/root/firefox_31.0+build1-0ubuntu0.14.04.1_amd64.deb
      sudo: yes

    - name: Restart xvfb
      service: name=xvfb state=restarted
      sudo: yes
